[package]
name = "project-rc"
version = "0.1.0"
authors = ["Michael Goulet <michael@errs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
